### ISSUE TITLE
feature - add maxjobs flag

### ISSUE THREAD

**Issue by thomasbeaudry** [CoBrALab/qbatch#224]
It would be good to add the maxjobs flag so SLURM could use it

**Comment by gdevenyi** [comment]
Can you be more specific as to what this means.

**Comment by thomasbeaudry** [comment]
https://slurm.schedmd.com/resource_limits.html#:~:text=association%20tree%20again.-,MaxJobs,-The%20total%20number

Being able to specify this flag lets you control the load you put on the system (i was thinking of the unzip example we had to deal with lately, but i'm sure there are other good uses)

**Comment by thomasbeaudry** [comment]
Actually, maxjobs is an accounting flag that can be set on a user basis, not a submission flag so forget about this request - my bad.

What I was thinking of is something like this:
[sbatch --array=1-100%10](https://docs.alliancecan.ca/wiki/Job_arrays#:~:text=sbatch%20%2D%2Darray%3D1%2D100%2510%20%20%23%20Allows%20no%20more%20than%2010%20of%20the%20jobs%20to%20run%20simultaneously)

Can we do this with qbatch currently?  I didn't see any reference to it.
